version: '3.7'

services:
  # wordpress database
  db:
    image: vk50630/mysql:tdr
    restart: on-failure
    cap_add:
      - SYS_NICE
    environment:
      MYSQL_DATABASE: wpdb
      MYSQL_USER: gudi
      MYSQL_PASSWORD: password
      MYSQL_RANDOM_ROOT_PASSWORD: '1'
    labels:
      hr.fer.diplomski.kolka.attack.label: false

  # wordpress server
  wordpress:
    image: vk50630/wordpress:tdr
    hostname: wordpress
    restart: on-failure
    ports:
      - 8000:80
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: gudi
      WORDPRESS_DB_PASSWORD: password
      WORDPRESS_DB_NAME: wpdb
      WORDPRESS_CONFIG_EXTRA: |
        define('WP_HOME', 'http://example.com');
        define('WP_SITEURL', 'http://example.com');
    labels:
      hr.fer.diplomski.kolka.attack.label: false
    depends_on:
      - db
    volumes:
      - ./wordpress-tdr-backup/:/var/www/html/wp-content/

  # scanning attack on the server
  droopescan:
    image: vk50630/droopescan:1.0
    entrypoint: "droopescan"
    command: "scan wordpress -u $SUT_ADDRESS"
    environment:
      MAX_SLEEP: "$MAX_SLEEP"
    labels:
      hr.fer.diplomski.kolka.attack.label: true
    depends_on:
      - wordpress

  # flightsim (a few classic attacks)
  flightsim:
    image: vk50630/flightsim:1.0
    command: "run"
    environment:
      MAX_SLEEP: "$MAX_SLEEP"
    labels:
      hr.fer.diplomski.kolka.attack.label: true
    depends_on:
      - wordpress

  # locust agent
  locust:
    image: locustio/locust
    labels:
      hr.fer.diplomski.kolka.attack.label: false
    volumes:
      - ./:/mnt/locust
    depends_on:
      - wordpress
    command: -f /mnt/locust/locustfile.py -u $USERS -r $SPAWN_RATE -H $SUT_ADDRESS --headless

networks:
  default:
    external:
      name: "$NETWORK_NAME"
