version: "3.7"

services:

  zookeeper:
    hostname: zookeeper
    image: zookeeper
    restart: on-failure
    network_mode: host

  kafka:
    image: confluentinc/cp-kafka
    hostname: kafka
    network_mode: host
    depends_on: [zookeeper]
    environment:
      KAFKA_ZOOKEEPER_CONNECT: "localhost:2181"
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_BROKER_ID: 1
      KAFKA_DEFAULT_REPLICATION_FACTOR: 1
      KAFKA_OFFSETS_STORAGE_REPLICATION_FACTOR: 1
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  localfilesink:
    image: vk50630/localfilesink:1.0
    depends_on: [kafka]
    restart: always
    network_mode: host
    environment:
      OUTPUT_FILE: $OUTPUT_FILE
      FLOW_CSV_LABELED: $FLOW_CSV_LABELED
    volumes:
    - "../data/:/data/"

  tcpdump:
    image: kaazing/tcpdump
    network_mode: host
    volumes:
      - ../data/:/data/
    command: "-i $INTERFACE -w $RAW_DATA_FILE"

  cicflowmeter:
    image: vk50630/cicflowmeter:1.0
    depends_on: [kafka]
    restart: always
    # has to run on host network to see the interface of generator network
    network_mode: host
    entrypoint: "python3"
    command: "sniffer.py -i $INTERFACE --flow --broker localhost:9092 --topic $FLOW_CSV_UNLABELED"
