version: '3.3'

services:

  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: wpdb
      MYSQL_USER: gudi
      MYSQL_PASSWORD: password
      MYSQL_RANDOM_ROOT_PASSWORD: '1'
    volumes:
      - db:/var/lib/mysql

  wordpress:
    image: wordpress
    hostname: wordpress
    restart: always
    ports:
      - 8080:80
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: gudi
      WORDPRESS_DB_PASSWORD: password
      WORDPRESS_DB_NAME: wpdb
      WORDPRESS_CONFIG_EXTRA: |
        define('WP_HOME', 'http://example.com');
        define('WP_SITEURL', 'http://example.com');
    depends_on:
      - db
    volumes:
      - wordpress:/var/www/html
  # moj mali container na koji se spojis i ima instaliran curl
  # docker exec -it ime_containera bash
  # curl wordpress
  curl:
    image: curl:client

volumes:
  wordpress:
  db:
